# Site settings
title: Cardboard Cabin
description:
  nl: "Band uit Kortrijk. Speelt traditionele folk op eigenwijze."
  en: "Band from Kortrijk, Belgium. Plays modern traditional music most of the time."
  fr: "Groupe qui joue la musique traditionelle moderne."
baseurl: "/cardboard_cabin" # the subpath of your site, e.g. /blog/
url: "https://awwerbro.github.io/cardboard_cabin/" # the base hostname & protocol for your site

plugins:
  - jekyll-polyglot

# User setting
owner: Cardboard Cabin
email: bookings@cardboardcabin.be
facebook_username: CardboardCabin
twitter_username:
github_username:
instagram_username: cardboardcabin/
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright: Flor Delombaerde & Andreas Werbrouck

# Permalinks
permalink: pretty

include: ['_pages']

languages: ["nl", "en", "fr"]
default_lang: "nl"
exclude_from_localization: ["javascript", "img", "css", "README.md"]
parallel_localization: false
lang_from_path: true

language_full:
  nl: Nederlands
  en: English
  fr: Français
  
carousel: 
  - image: public/carousel/image1.jpg
  - image: public/carousel/image2.jpg
  - image: public/carousel/image3.jpg
  - image: public/carousel/image4.jpg
  - image: public/carousel/image5.jpg
  - image: public/carousel/image6.jpg
  - image: public/carousel/image7.jpg
  
# Build settings
markdown: kramdown
